# Generated by Django 5.0.7 on 2024-09-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('father_name', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=95, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('non_urgent', 'Non-Urgent'), ('chronic', 'Chronic Condition Management'), ('preventive', 'Preventive Care'), ('specialist', 'Specialist Referral'), ('follow_up', 'Follow-Up')], max_length=20, null=True)),
                ('problem', models.CharField(choices=[('medi_surg', 'Medical/Surgical'), ('trauma', 'Trauma'), ('obstetrics_gynecology', 'Obstetrics/Gynecology'), ('pediatric', 'Pediatric'), ('geriatric', 'Geriatric'), ('mental_health', 'Psychiatry/Mental Health'), ('oncology', 'Oncology'), ('rehabilitation', 'Rehabilitation'), ('infection', 'Infection Disease'), ('chronic', 'Chronic Disease'), ('special_care', 'Special Care')], max_length=30)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, null=True)),
                ('taking_any_medicines', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
